// <auto-generated />
namespace receitasall.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration22345 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration22345));
        
        string IMigrationMetadata.Id
        {
            get { return "202410272332086_migration22345"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
