// <auto-generated />
namespace receitasall.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SeedDefaultUsers3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedDefaultUsers3));
        
        string IMigrationMetadata.Id
        {
            get { return "202411030328342_SeedDefaultUsers3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
